AllCops:
AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes


Metrics/LineLength:
  Max: 100


Layout/IndentationWidth:
  Width: 2

Style/Documentation:
  Enabled: false


Metrics/MethodLength:
  Max: 10 # Limit the maximum number of lines per method

